### ISSUE TITLE
`ftw download` call without arguments fails

### ISSUE THREAD

**Issue by cholmes** [fieldsoftheworld/ftw-baselines#11]
If I just say `ftw download` then I get the error below. It worked fine with `ftw download --countries all`. I think we should just default to 'all' if no arguments are supplied. I can fix this pretty easily, but I'm about done for the day, so just noting it here in case someone else wants to grab it.

```
Traceback (most recent call last):
  File "/Users/cholmes/miniforge3/envs/ftw4/bin/ftw", line 8, in <module>
    sys.exit(ftw())
             ^^^^^
  File "/Users/cholmes/miniforge3/envs/ftw4/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cholmes/miniforge3/envs/ftw4/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/cholmes/miniforge3/envs/ftw4/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cholmes/miniforge3/envs/ftw4/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cholmes/miniforge3/envs/ftw4/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cholmes/repos/ftw-baselines/src/ftw_cli/download.py", line 227, in download
    country_names = [country.lower().strip() for country in countries.split(',') if country.lower().strip() in all_countries]
```

**Comment by aninda-ghosh** [comment]
@cholmes please review and approve.

https://github.com/fieldsoftheworld/ftw-baselines/pull/18
